# Generated by Django 4.2.20 on 2025-10-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_entradaproducto_numero_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproducto',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='costo_compra',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='costo_venta',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='imei_serial',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='margen_ganancia',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='monto_itbis',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='numero_maquina',
        ),
        migrations.RemoveField(
            model_name='entradaproducto',
            name='porcentaje_itbis',
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='compatibilidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compatibilidad'),
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Costo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='descripcion',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='precio_por_mayor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Mayor'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='color',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('azul', 'Azul'), ('rojo', 'Rojo'), ('dorado', 'Dorado'), ('plateado', 'Plateado'), ('verde', 'Verde'), ('morado', 'Morado'), ('rosa', 'Rosa'), ('gris', 'Gris'), ('otros', 'Otros')], max_length=20),
        ),
    ]
