# Generated by Django 4.2.20 on 2025-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_remove_entradaproducto_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='monto_total_con_interes',
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total'),
        ),
    ]
