# Generated by Django 4.2.20 on 2025-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_remove_cuentaporcobrar_monto_total_con_interes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cuota_mensual',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='es_financiada',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='interes_mensual',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='interes_total',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='monto_financiado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='plazo_meses',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tasa_interes',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_a_pagar',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_con_interes',
        ),
        migrations.AlterField(
            model_name='venta',
            name='montoinicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
