# Generated by Django 4.2.20 on 2025-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_remove_venta_cuota_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='itbis_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='itbis_porcentaje',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
