# Generated by Django 4.2.20 on 2025-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_venta_itbis_monto_venta_itbis_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='porcentaje_itbis',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Porcentaje ITBIS'),
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='precio_con_itbis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio con ITBIS'),
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='precio_por_mayor_con_itbis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Mayor con ITBIS'),
        ),
    ]
