# Generated by Django 4.2.20 on 2025-10-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_venta_total_a_pagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
