# Generated by Django 4.2.20 on 2025-10-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0028_alter_venta_options_alter_venta_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas',
        ),
    ]
