# Generated by Django 4.2.20 on 2025-10-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_alter_venta_options_alter_venta_numero_factura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
