# Generated by Django 4.2.20 on 2025-10-09 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_alter_venta_options_alter_venta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='porcentaje_mayor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente: ((precio_por_mayor - costo) / costo * 100)', max_digits=5, null=True, verbose_name='Porcentaje por Mayor Calculado'),
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='porcentaje_minorista',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente: ((precio - costo) / costo * 100)', max_digits=5, null=True, verbose_name='Porcentaje Minorista Calculado'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='color',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco'), ('azul', 'Azul'), ('rojo', 'Rojo'), ('dorado', 'Dorado'), ('plateado', 'Plateado'), ('verde', 'Verde'), ('morado', 'Morado'), ('rosa', 'Rosa'), ('gris', 'Gris'), ('otros', 'Otros')], max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Base'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='es_producto_base',
            field=models.BooleanField(default=False, verbose_name='Es Producto Base'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='marca',
            field=models.CharField(choices=[('honda', 'Honda'), ('yamaha', 'Yamaha'), ('suzuki', 'Suzuki'), ('kawasaki', 'Kawasaki'), ('tvs', 'TVS'), ('hero', 'Hero'), ('loncin', 'Loncin'), ('kove', 'Kove'), ('x1000', 'X1000'), ('ktm', 'KTM'), ('bajaj', 'Bajaj'), ('super vestia', 'Super Vestia'), ('otros', 'Otros')], max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='ncf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NCF'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='numero_factura',
            field=models.CharField(max_length=50, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Minorista'),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='entradaproducto',
            index=models.Index(fields=['codigo_producto'], name='facturacion_codigo__470fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaproducto',
            index=models.Index(fields=['marca'], name='facturacion_marca_1b75ee_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaproducto',
            index=models.Index(fields=['activo'], name='facturacion_activo_3b6f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaproducto',
            index=models.Index(fields=['fecha_entrada'], name='facturacion_fecha_e_861e5e_idx'),
        ),
    ]
