# Generated by Django 4.2.20 on 2025-11-07 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0034_cuentaporpagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='fecha_emision',
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='fecha_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrada'),
        ),
    ]
