# Generated by Django 4.2.20 on 2025-11-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0035_remove_cuentaporpagar_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentaporpagar',
            options={'ordering': ['estado', 'fecha_vencimiento', '-fecha_registro'], 'verbose_name': 'Cuenta por Pagar', 'verbose_name_plural': 'Cuentas por Pagar'},
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='producto',
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito')], max_length=20, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='notas_pago',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Pago'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago'),
        ),
        migrations.CreateModel(
            name='DetalleCuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.cuentaporpagar')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.entradaproducto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Cuenta por Pagar',
                'verbose_name_plural': 'Detalles Cuentas por Pagar',
            },
        ),
    ]
