# Generated by Django 4.2.20 on 2025-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_alter_cuentaporpagar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrecaja',
            options={'ordering': ['-fecha_cierre'], 'verbose_name': 'Cierre de Caja', 'verbose_name_plural': 'Cierres de Caja'},
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='hora_cierre_exacta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='tipo_cierre',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=10),
        ),
    ]
