# Generated by Django 4.2.20 on 2026-01-25 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0038_alter_caja_fecha_apertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('pago', 'Pago'), ('devolucion', 'Devolución'), ('ajuste', 'Ajuste'), ('interes', 'Interés'), ('descuento', 'Descuento')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='facturacion.cuentaporcobrar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Cuenta por Cobrar',
                'verbose_name_plural': 'Movimientos de Cuentas por Cobrar',
                'db_table': 'movimientos_cuenta_por_cobrar',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
