# Generated by Django 4.2.20 on 2025-10-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0030_alter_venta_options_alter_venta_numero_factura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas',
        ),
    ]
