# Generated by Django 4.2.20 on 2025-10-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('facturacion', '0032_entradaproducto_porcentaje_mayor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='marca',
            field=models.CharField(choices=[('honda', 'Honda'), ('yamaha', 'Yamaha'), ('suzuki', 'Suzuki'), ('kawasaki', 'Kawasaki'), ('tvs', 'TVS'), ('hero', 'Hero'), ('loncin', 'Loncin'), ('kove', 'Kove'), ('x1000', 'X1000'), ('ktm', 'KTM'), ('bajaj', 'Bajaj'), ('super Bestia', 'Super Bestia'), ('otros', 'Otros')], max_length=20, verbose_name='Marca'),
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('es_global', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_extension', to='auth.group')),
            ],
        ),
    ]
