# Generated by Django 4.2.20 on 2025-12-18 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0037_alter_cierrecaja_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
