# Generated by Django 4.2.20 on 2026-03-03 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0039_movimientocuentaporcobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuentaporcobrar',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cobró'),
            preserve_default=False,
        ),
    ]
