# Generated by Django 4.2.20 on 2026-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0040_pagocuentaporcobrar_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AddField(
            model_name='devolucion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagocuentaporcobrar',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de descuento aplicado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_devolucion',
            field=models.CharField(choices=[('sin_devolucion', 'Sin devolución'), ('parcial', 'Devolución parcial'), ('total', 'Devolución total')], default='sin_devolucion', max_length=20),
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
