# Generated by Django 4.2.20 on 2026-04-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0041_devolucion_monto_venta_estado_devolucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
