# Generated by Django 4.2.20 on 2026-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0041_alter_venta_options_devolucion_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentaporcobrar',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('descuento', 'Descuento')], max_length=15, verbose_name='Método de Pago'),
        ),
    ]
