# Generated by Django 4.2.20 on 2026-04-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0042_alter_pagocuentaporcobrar_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='tipo_precio',
            field=models.CharField(choices=[('unitaria', 'Venta Unitaria'), ('mayor', 'Venta por Mayor')], default='unitaria', max_length=10, verbose_name='Tipo de precio aplicado'),
        ),
    ]
