# Generated by Django 4.2.20 on 2026-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0043_detalleventa_tipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuentaporcobrar',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('descuento', 'Descuento'), ('ajuste', 'Ajuste')], max_length=15, verbose_name='Método de Pago'),
        ),
    ]
